[phases.setup]
nixPkgs = [
    "nodejs-18_x",
    "python3",
    "gcc",
    "gnumake"
]

[env]
NODE_ENV = "production"
PATH = "/usr/local/bin:/usr/bin:${PATH}"

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"
watchPatterns = ["server.js", "execution/**"]
